name: pdf_shop_app
description: PDF Shop application
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path_provider: ^2.1.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  syncfusion_flutter_pdfviewer: ^28.2.7
  file_picker: ^8.1.2
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
